### ISSUE TITLE
Provide conda packages

### ISSUE THREAD

**Issue by xhochy** [cwida/duckdb#225]
It would be nice to have `conda` packages for the R and Python interfaces. I've tried to setup them up but run into some issues and will this issue here as a meta-issue to collect what needs to be done:

- [x]  CMake install target: https://github.com/cwida/duckdb/issues/223
- [x] `make_unique` is ambiguous on old OSX SDK: https://github.com/cwida/duckdb/issues/224
- [x] `pip install` doesn't work: https://github.com/cwida/duckdb/issues/227
- [x] Reuse built library: https://github.com/cwida/duckdb/issues/228
- [x] Namespace header files: https://github.com/cwida/duckdb/issues/229
- [x] `pytest-runner` is required as install dependency: https://github.com/cwida/duckdb/pull/230

**Comment by hannesmuehleisen** [comment]
Indeed it would be nice. I have no experience with conda, so help is appreciated.

**Comment by xhochy** [comment]
We have conda package now for Python: https://github.com/conda-forge/python-duckdb-feedstock, I'll also have a look at making one for C++ but that requires the above mentioned points.

Could you add to the documentation that you can install this via `conda install python-duckdb -c conda-forge`? I couldn't find the sources of it so I was unable to make a PR on my own.

**Comment by hannesmuehleisen** [comment]
I have added a note to the documentation, thanks a lot for your work on making this possible!

**Comment by xhochy** [comment]
This is now available as `libduckdb` as part of the `duckdb-split-feedstock`.
